//! Rust source generation for validated analysis specs.
//!
//! This is intentionally a narrow first slice: it emits a single producer with
//! object cuts, count-based region requirements, `count(...)` outputs, and
//! `leading(...).pt`-style floating-point outputs.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;
use std::fmt::Write as _;

use nano_core::BranchType;

use crate::{AnalysisSpec, CmpOp, Expr, ObjectDef, ResolvedPlan};

/// Generate compilable Rust producer source from a validated plan.
///
/// The caller should obtain the plan from [`crate::validate`]. Code generation
/// assumes validation has already resolved branch existence and semantic object
/// references; this layer rejects only forms outside the first codegen slice.
pub fn generate_producer_source(plan: &ResolvedPlan) -> Result<String, CodegenError> {
    Generator { plan }.generate()
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CodegenError {
    InvalidIdentifier { context: String, value: String },
    UnsupportedFeature(String),
}

impl fmt::Display for CodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidIdentifier { context, value } => {
                write!(f, "{context}: `{value}` is not a supported Rust identifier")
            }
            Self::UnsupportedFeature(detail) => f.write_str(detail),
        }
    }
}

impl Error for CodegenError {}

struct Generator<'a> {
    plan: &'a ResolvedPlan,
}

impl<'a> Generator<'a> {
    fn generate(&self) -> Result<String, CodegenError> {
        self.validate_supported_spec()?;

        let mut source = String::new();
        writeln!(
            source,
            "// @generated by nano-spec from analysis `{}`. Do not edit by hand.",
            self.spec().name
        )
        .unwrap();
        writeln!(source).unwrap();
        writeln!(source, "#[derive(Debug, Clone, Copy, PartialEq)]").unwrap();
        writeln!(source, "pub struct GenRow {{").unwrap();
        for output in &self.spec().outputs {
            writeln!(
                source,
                "    pub {}: {},",
                checked_ident(&output.name, "output field")?,
                self.output_type(&output.expr)?
            )
            .unwrap();
        }
        writeln!(source, "}}").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "pub struct GeneratedProducer;").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "impl GeneratedProducer {{").unwrap();
        writeln!(
            source,
            "    pub fn analyze(event: &nano_core::Event) -> nano_core::Result<Option<GenRow>> {{"
        )
        .unwrap();

        for object in &self.spec().objects {
            self.emit_object_selection(&mut source, object)?;
        }

        for region in &self.spec().regions {
            for requirement in &region.require {
                let condition = self.emit_region_requirement(
                    &requirement.lhs,
                    requirement.op,
                    requirement.rhs,
                )?;
                writeln!(source, "        if !({condition}) {{").unwrap();
                writeln!(source, "            return Ok(None);").unwrap();
                writeln!(source, "        }}").unwrap();
            }
        }

        for output in &self.spec().outputs {
            if matches!(output.expr, Expr::LeadingAttr { .. }) {
                let name = checked_ident(&output.name, "leading output")?;
                writeln!(source, "        let Some({name}) = {name} else {{").unwrap();
                writeln!(source, "            return Ok(None);").unwrap();
                writeln!(source, "        }};").unwrap();
            }
        }

        writeln!(source, "        Ok(Some(GenRow {{").unwrap();
        for output in &self.spec().outputs {
            let field = checked_ident(&output.name, "output field")?;
            let expr = self.emit_output_expr(&output.expr, &field)?;
            writeln!(source, "            {field}: {expr},").unwrap();
        }
        writeln!(source, "        }}))").unwrap();
        writeln!(source, "    }}").unwrap();
        writeln!(source, "}}").unwrap();

        Ok(source)
    }

    fn spec(&self) -> &AnalysisSpec {
        &self.plan.spec
    }

    fn validate_supported_spec(&self) -> Result<(), CodegenError> {
        if !self.spec().models.is_empty() {
            return Err(CodegenError::UnsupportedFeature(
                "model bindings are validated, but this codegen slice does not emit inference"
                    .to_string(),
            ));
        }

        for object in &self.spec().objects {
            checked_ident(&object.name, "object name")?;
            checked_ident(&object.source, "object source")?;
            for cut in &object.cuts {
                self.validate_cut_expr(&object.name, &cut.lhs)?;
            }
        }

        for region in &self.spec().regions {
            checked_ident(&region.name, "region name")?;
            for requirement in &region.require {
                self.validate_count_expr(&requirement.lhs, "region requirement")?;
                checked_count_rhs(requirement.rhs, "region requirement")?;
            }
        }

        for output in &self.spec().outputs {
            checked_ident(&output.name, "output name")?;
            match &output.expr {
                Expr::Count(object) => {
                    self.object(object)?;
                }
                Expr::LeadingAttr { object, attr } => {
                    if attr != "pt" {
                        return Err(CodegenError::UnsupportedFeature(format!(
                            "leading output `{}` uses `{attr}`; this slice only supports leading(...).pt",
                            output.name
                        )));
                    }
                    self.require_f32_attr(object, attr, "leading output")?;
                }
                other => {
                    return Err(CodegenError::UnsupportedFeature(format!(
                        "output `{}` uses unsupported expression `{other}`",
                        output.name
                    )));
                }
            }
        }

        Ok(())
    }

    fn emit_object_selection(
        &self,
        source: &mut String,
        object: &ObjectDef,
    ) -> Result<(), CodegenError> {
        let object_name = checked_ident(&object.name, "object name")?;
        let collection_ident = format!("{object_name}_collection");
        let item_ident = format!("{object_name}_item");
        let count_ident = count_ident(&object.name)?;
        let attrs = self.attrs_needed_for_object(&object.name)?;

        writeln!(
            source,
            "        let {collection_ident} = event.collection({})?;",
            rust_string(&object.source)
        )
        .unwrap();
        writeln!(source, "        let mut {count_ident} = 0_u32;").unwrap();

        for output in &self.spec().outputs {
            if let Expr::LeadingAttr {
                object: output_object,
                ..
            } = &output.expr
            {
                if output_object == &object.name {
                    let output_name = checked_ident(&output.name, "leading output")?;
                    writeln!(source, "        let mut {output_name}: Option<f32> = None;").unwrap();
                }
            }
        }

        writeln!(source).unwrap();
        writeln!(
            source,
            "        for {item_ident} in {collection_ident}.iter() {{"
        )
        .unwrap();

        for attr in attrs {
            self.require_f32_attr(&object.name, &attr, "object attribute")?;
            let attr_ident = attr_ident(&object.name, &attr)?;
            writeln!(
                source,
                "            let {attr_ident} = {item_ident}.get::<f32>({})?;",
                rust_string(&attr)
            )
            .unwrap();
        }

        let condition = if object.cuts.is_empty() {
            "true".to_string()
        } else {
            object
                .cuts
                .iter()
                .map(|cut| self.emit_cut(object, cut))
                .collect::<Result<Vec<_>, _>>()?
                .join(" && ")
        };

        writeln!(source, "            if {condition} {{").unwrap();
        writeln!(source, "                {count_ident} += 1;").unwrap();

        for output in &self.spec().outputs {
            if let Expr::LeadingAttr {
                object: output_object,
                attr,
            } = &output.expr
            {
                if output_object == &object.name {
                    let output_name = checked_ident(&output.name, "leading output")?;
                    let attr_ident = attr_ident(&object.name, attr)?;
                    writeln!(source, "                {output_name} = Some(").unwrap();
                    writeln!(
                        source,
                        "                    {output_name}.map_or({attr_ident}, |lead| lead.max({attr_ident})),"
                    )
                    .unwrap();
                    writeln!(source, "                );").unwrap();
                }
            }
        }

        writeln!(source, "            }}").unwrap();
        writeln!(source, "        }}").unwrap();
        writeln!(source).unwrap();
        Ok(())
    }

    fn attrs_needed_for_object(&self, object_name: &str) -> Result<BTreeSet<String>, CodegenError> {
        let mut attrs = BTreeSet::new();
        let object = self.object(object_name)?;
        for cut in &object.cuts {
            collect_attr_names_for_current_object(&cut.lhs, object_name, &mut attrs)?;
        }
        for output in &self.spec().outputs {
            if let Expr::LeadingAttr { object, attr } = &output.expr {
                if object == object_name {
                    attrs.insert(attr.clone());
                }
            }
        }
        Ok(attrs)
    }

    fn emit_cut(&self, object: &ObjectDef, cut: &crate::Cut) -> Result<String, CodegenError> {
        let lhs = self.emit_cut_value_expr(&cut.lhs, &object.name)?;
        let op = cmp_op(cut.op);
        let rhs = f32_literal(cut.rhs.value);
        Ok(format!("({lhs} {op} {rhs})"))
    }

    fn emit_cut_value_expr(&self, expr: &Expr, object_name: &str) -> Result<String, CodegenError> {
        match expr {
            Expr::Attr { object, attr } if object == object_name => {
                attr_ident(object_name, attr)
            }
            Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
                "object cut references `{object}`; this slice only supports cuts on the object being selected"
            ))),
            Expr::Abs(inner) => Ok(format!("{}.abs()", self.emit_cut_value_expr(inner, object_name)?)),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "object cut expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn emit_region_requirement(
        &self,
        lhs: &Expr,
        op: CmpOp,
        rhs: f64,
    ) -> Result<String, CodegenError> {
        let Expr::Count(object) = lhs else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "region requirement `{lhs}` is not supported by this slice"
            )));
        };
        let lhs = count_ident(object)?;
        let rhs = checked_count_rhs(rhs, "region requirement")?;
        Ok(format!("{lhs} {} {rhs}_u32", cmp_op(op)))
    }

    fn emit_output_expr(&self, expr: &Expr, output_name: &str) -> Result<String, CodegenError> {
        match expr {
            Expr::Count(object) => count_ident(object),
            Expr::LeadingAttr { .. } => Ok(output_name.to_string()),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "output expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn output_type(&self, expr: &Expr) -> Result<&'static str, CodegenError> {
        match expr {
            Expr::Count(_) => Ok("u32"),
            Expr::LeadingAttr { .. } => Ok("f32"),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "output expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn validate_cut_expr(&self, object_name: &str, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::Attr { object, attr } if object == object_name => {
                self.require_f32_attr(object, attr, "object cut")?;
                Ok(())
            }
            Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
                "object `{object_name}` cut references `{object}`; this slice only supports cuts on the object being selected"
            ))),
            Expr::Abs(inner) => self.validate_cut_expr(object_name, inner),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "object cut expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn validate_count_expr(&self, expr: &Expr, context: &str) -> Result<(), CodegenError> {
        let Expr::Count(object) = expr else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context} expression `{expr}` is not supported by this slice"
            )));
        };
        self.object(object)?;
        Ok(())
    }

    fn require_f32_attr(
        &self,
        object_name: &str,
        attr: &str,
        context: &str,
    ) -> Result<(), CodegenError> {
        let object = self.object(object_name)?;
        let branch = format!("{}_{}", object.source, attr);
        let Some(info) = self.plan.read_branches.find(&branch) else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context}: branch `{branch}` was not present in the validated read schema"
            )));
        };
        if info.branch_type != BranchType::VecF32 {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context}: branch `{branch}` has type {:?}; this slice only emits f32 object reads",
                info.branch_type
            )));
        }
        Ok(())
    }

    fn object(&self, name: &str) -> Result<&ObjectDef, CodegenError> {
        self.spec()
            .objects
            .iter()
            .find(|object| object.name == name)
            .ok_or_else(|| {
                CodegenError::UnsupportedFeature(format!(
                    "object `{name}` is not defined in the analysis spec"
                ))
            })
    }
}

fn collect_attr_names_for_current_object(
    expr: &Expr,
    object_name: &str,
    attrs: &mut BTreeSet<String>,
) -> Result<(), CodegenError> {
    match expr {
        Expr::Attr { object, attr } if object == object_name => {
            attrs.insert(attr.clone());
            Ok(())
        }
        Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
            "object `{object_name}` cut references `{object}`; this slice only supports cuts on the object being selected"
        ))),
        Expr::Abs(inner) => collect_attr_names_for_current_object(inner, object_name, attrs),
        other => Err(CodegenError::UnsupportedFeature(format!(
            "object cut expression `{other}` is not supported by this slice"
        ))),
    }
}

fn count_ident(object_name: &str) -> Result<String, CodegenError> {
    Ok(format!("n_{}", checked_ident(object_name, "count object")?))
}

fn attr_ident(object_name: &str, attr: &str) -> Result<String, CodegenError> {
    Ok(format!(
        "{}_{}",
        checked_ident(object_name, "attribute object")?,
        checked_ident(attr, "attribute")?
    ))
}

fn checked_ident(value: &str, context: &str) -> Result<String, CodegenError> {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return Err(CodegenError::InvalidIdentifier {
            context: context.to_string(),
            value: value.to_string(),
        });
    };
    if !(first == '_' || first.is_ascii_alphabetic())
        || !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        || rust_keywords().contains_key(value)
    {
        return Err(CodegenError::InvalidIdentifier {
            context: context.to_string(),
            value: value.to_string(),
        });
    }
    Ok(value.to_string())
}

fn rust_keywords() -> BTreeMap<&'static str, ()> {
    [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn",
    ]
    .into_iter()
    .map(|keyword| (keyword, ()))
    .collect()
}

fn cmp_op(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Gt => ">",
        CmpOp::Ge => ">=",
        CmpOp::Lt => "<",
        CmpOp::Le => "<=",
        CmpOp::Eq => "==",
        CmpOp::Ne => "!=",
    }
}

fn f32_literal(value: f64) -> String {
    format!("{value:?}_f32")
}

fn checked_count_rhs(value: f64, context: &str) -> Result<u32, CodegenError> {
    if value.is_finite() && value >= 0.0 && value.fract() == 0.0 && value <= u32::MAX as f64 {
        Ok(value as u32)
    } else {
        Err(CodegenError::UnsupportedFeature(format!(
            "{context}: count comparison rhs `{value}` is not a non-negative u32 integer"
        )))
    }
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{validate, AnalysisSpec, Catalogue};

    const MUON_SPEC: &str = include_str!("../examples/muon.toml");
    const NANOV9_CATALOGUE: &str = include_str!("../../../configs/branches/nanov9.yaml");

    #[test]
    fn generates_muon_producer_source() {
        let spec = AnalysisSpec::from_toml_str(MUON_SPEC).unwrap();
        let catalogue = Catalogue::from_nanoaod_yaml_str(NANOV9_CATALOGUE, "v9").unwrap();
        let plan = validate(&spec, &catalogue).unwrap();
        let source = generate_producer_source(&plan).unwrap();

        assert!(source.contains("pub struct GenRow"));
        assert!(source.contains("pub struct GeneratedProducer;"));
        assert!(source.contains("let good_muon_pt = good_muon_item.get::<f32>(\"pt\")?;"));
        assert!(source.contains("if (good_muon_pt > 30.0_f32) && (good_muon_eta.abs() < 2.4_f32)"));
        assert!(source.contains("n_good_muon: n_good_muon,"));
        assert!(source.contains("lead_muon_pt: lead_muon_pt,"));
    }
}
