//! Rust source generation for validated analysis specs.
//!
//! This is intentionally a narrow first slice: it emits a single producer with
//! object cuts, count-based region requirements, `count(...)` outputs, and
//! `leading(...).pt`-style floating-point outputs.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;
use std::fmt::Write as _;

use nano_core::BranchType;

use crate::{AnalysisSpec, CmpOp, Expr, ModelDef, ObjectDef, ResolvedPlan};

/// Generate compilable Rust producer source from a validated plan.
///
/// The caller should obtain the plan from [`crate::validate`]. Code generation
/// assumes validation has already resolved branch existence and semantic object
/// references; this layer rejects only forms outside the first codegen slice.
pub fn generate_producer_source(plan: &ResolvedPlan) -> Result<String, CodegenError> {
    Generator { plan }.generate()
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CodegenError {
    InvalidIdentifier { context: String, value: String },
    UnsupportedFeature(String),
}

impl fmt::Display for CodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidIdentifier { context, value } => {
                write!(f, "{context}: `{value}` is not a supported Rust identifier")
            }
            Self::UnsupportedFeature(detail) => f.write_str(detail),
        }
    }
}

impl Error for CodegenError {}

struct Generator<'a> {
    plan: &'a ResolvedPlan,
}

impl<'a> Generator<'a> {
    fn generate(&self) -> Result<String, CodegenError> {
        if self.spec().models.is_empty() {
            return self.generate_without_models();
        }
        self.generate_with_models()
    }

    fn generate_without_models(&self) -> Result<String, CodegenError> {
        self.validate_supported_spec()?;

        let mut source = String::new();
        writeln!(
            source,
            "// @generated by nano-spec from analysis `{}`. Do not edit by hand.",
            self.spec().name
        )
        .unwrap();
        self.emit_region_markers(&mut source)?;
        writeln!(source).unwrap();
        writeln!(source, "#[derive(Debug, Clone, Copy, PartialEq)]").unwrap();
        writeln!(source, "pub struct GenRow {{").unwrap();
        for output in &self.spec().outputs {
            writeln!(
                source,
                "    pub {}: {},",
                checked_ident(&output.name, "output field")?,
                self.output_type(&output.expr)?
            )
            .unwrap();
        }
        writeln!(source, "}}").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "pub struct GeneratedProducer;").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "impl GeneratedProducer {{").unwrap();
        writeln!(
            source,
            "    pub fn analyze(event: &nano_core::Event) -> nano_core::Result<Option<GenRow>> {{"
        )
        .unwrap();

        for object in &self.spec().objects {
            self.emit_object_selection(&mut source, object)?;
        }

        if !self.spec().regions.is_empty() {
            writeln!(
                source,
                "        let baseline = nano_analysis::Ev::new(event)"
            )
            .unwrap();
            writeln!(source, "            .preselect(|_| true)").unwrap();
            writeln!(
                source,
                "            .expect(\"true generated preselection should always pass\");"
            )
            .unwrap();
            self.emit_region_selections(&mut source, "baseline")?;
        }

        for output in &self.spec().outputs {
            if matches!(output.expr, Expr::LeadingAttr { .. }) {
                let name = checked_ident(&output.name, "leading output")?;
                writeln!(source, "        let Some({name}) = {name} else {{").unwrap();
                writeln!(source, "            return Ok(None);").unwrap();
                writeln!(source, "        }};").unwrap();
            }
        }

        writeln!(source, "        Ok(Some(GenRow {{").unwrap();
        for output in &self.spec().outputs {
            let field = checked_ident(&output.name, "output field")?;
            let expr = self.emit_output_expr(&output.expr, &field)?;
            if field == expr {
                writeln!(source, "            {field},").unwrap();
            } else {
                writeln!(source, "            {field}: {expr},").unwrap();
            }
        }
        writeln!(source, "        }}))").unwrap();
        writeln!(source, "    }}").unwrap();
        writeln!(source, "}}").unwrap();

        Ok(source)
    }

    fn generate_with_models(&self) -> Result<String, CodegenError> {
        self.validate_supported_spec()?;

        let mut source = String::new();
        writeln!(
            source,
            "// @generated by nano-spec from analysis `{}`. Do not edit by hand.",
            self.spec().name
        )
        .unwrap();
        self.emit_region_markers(&mut source)?;
        writeln!(source).unwrap();
        writeln!(
            source,
            "type GenResult<T> = std::result::Result<T, nano_inference::InferError>;"
        )
        .unwrap();
        writeln!(source).unwrap();
        writeln!(
            source,
            "fn gen_core_error(error: impl std::fmt::Display) -> nano_inference::InferError {{"
        )
        .unwrap();
        writeln!(
            source,
            "    nano_inference::InferError::Feature(error.to_string())"
        )
        .unwrap();
        writeln!(source, "}}").unwrap();

        for model in &self.spec().models {
            self.emit_model_tag(&mut source, model)?;
        }

        writeln!(source).unwrap();
        writeln!(source, "#[derive(Debug, Clone, Copy, PartialEq)]").unwrap();
        writeln!(source, "pub struct GenRow {{").unwrap();
        for output in &self.spec().outputs {
            writeln!(
                source,
                "    pub {}: {},",
                checked_ident(&output.name, "output field")?,
                self.output_type(&output.expr)?
            )
            .unwrap();
        }
        writeln!(source, "}}").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "pub struct GeneratedProducer;").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "impl GeneratedProducer {{").unwrap();
        writeln!(
            source,
            "    pub fn analyze(event: &nano_core::Event, predictor: &impl nano_inference::Predictor) -> GenResult<Option<GenRow>> {{"
        )
        .unwrap();

        for model in &self.spec().models {
            self.emit_model_inference(&mut source, model)?;
        }
        let baseline_ident = self
            .spec()
            .models
            .first()
            .map(|model| checked_ident(&model.name, "model name"))
            .transpose()?
            .map(|model_ident| format!("{model_ident}_baseline"));

        let leading_region_exprs = self.leading_region_exprs();
        for object in &self.spec().objects {
            self.emit_model_object_selection(&mut source, &object.name)?;
        }

        let mut unwrapped_leading = BTreeSet::new();
        for region in &self.spec().regions {
            let mut conditions = Vec::with_capacity(region.require.len());
            for requirement in &region.require {
                let condition = self.emit_model_region_requirement(
                    &requirement.lhs,
                    requirement.op,
                    requirement.rhs,
                    &mut source,
                    &mut unwrapped_leading,
                )?;
                conditions.push(condition);
            }
            if let Some(baseline_ident) = &baseline_ident {
                self.emit_region_selection(&mut source, &region.name, baseline_ident, &conditions)?;
            }
        }

        for output in &self.spec().outputs {
            if let Expr::LeadingAttr { object, attr } = &output.expr {
                let key = (object.clone(), attr.clone());
                if leading_region_exprs.contains(&key) {
                    continue;
                }
                let ident = leading_attr_ident(object, attr)?;
                writeln!(source, "        let Some({ident}) = {ident} else {{").unwrap();
                writeln!(source, "            return Ok(None);").unwrap();
                writeln!(source, "        }};").unwrap();
            }
        }

        writeln!(source, "        Ok(Some(GenRow {{").unwrap();
        for output in &self.spec().outputs {
            let field = checked_ident(&output.name, "output field")?;
            let expr = self.emit_model_output_expr(&output.expr)?;
            if field == expr {
                writeln!(source, "            {field},").unwrap();
            } else {
                writeln!(source, "            {field}: {expr},").unwrap();
            }
        }
        writeln!(source, "        }}))").unwrap();
        writeln!(source, "    }}").unwrap();
        writeln!(source, "}}").unwrap();

        Ok(source)
    }

    fn spec(&self) -> &AnalysisSpec {
        &self.plan.spec
    }

    fn validate_supported_spec(&self) -> Result<(), CodegenError> {
        for object in &self.spec().objects {
            checked_ident(&object.name, "object name")?;
            checked_ident(&object.source, "object source")?;
            for cut in &object.cuts {
                self.validate_cut_expr(&object.name, &cut.lhs)?;
            }
        }

        for region in &self.spec().regions {
            checked_ident(&region.name, "region name")?;
            for requirement in &region.require {
                if self.spec().models.is_empty() {
                    self.validate_count_expr(&requirement.lhs, "region requirement")?;
                    checked_count_rhs(requirement.rhs, "region requirement")?;
                } else {
                    self.validate_model_region_expr(&requirement.lhs, "region requirement")?;
                }
            }
        }

        for output in &self.spec().outputs {
            checked_ident(&output.name, "output name")?;
            match &output.expr {
                Expr::Count(object) => {
                    self.object(object)?;
                }
                Expr::LeadingAttr { object, attr } => {
                    if self.spec().models.is_empty() && attr != "pt" {
                        return Err(CodegenError::UnsupportedFeature(format!(
                            "leading output `{}` uses `{attr}`; this slice only supports leading(...).pt",
                            output.name
                        )));
                    }
                    self.require_f32_attr(object, attr, "leading output")?;
                }
                other => {
                    return Err(CodegenError::UnsupportedFeature(format!(
                        "output `{}` uses unsupported expression `{other}`",
                        output.name
                    )));
                }
            }
        }

        for model in &self.spec().models {
            checked_ident(&model.name, "model name")?;
            self.model_type_ident(model)?;
            self.model_batch_source(model)?;
            let (_, output_attr) = split_model_output(&model.output)?;
            checked_ident(output_attr, "model output attribute")?;
            for input in &model.inputs {
                self.validate_model_input(model, input)?;
            }
        }

        Ok(())
    }

    fn emit_region_markers(&self, source: &mut String) -> Result<(), CodegenError> {
        for region in &self.spec().regions {
            let type_ident = region_type_ident(&region.name)?;
            writeln!(source).unwrap();
            writeln!(
                source,
                "#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]"
            )
            .unwrap();
            writeln!(source, "struct {type_ident};").unwrap();
            writeln!(source).unwrap();
            writeln!(source, "impl nano_analysis::Region for {type_ident} {{").unwrap();
            writeln!(
                source,
                "    const NAME: &'static str = {};",
                rust_string(&region.name)
            )
            .unwrap();
            writeln!(source, "}}").unwrap();
        }
        Ok(())
    }

    fn emit_region_selections(
        &self,
        source: &mut String,
        baseline_ident: &str,
    ) -> Result<(), CodegenError> {
        for region in &self.spec().regions {
            let conditions = region
                .require
                .iter()
                .map(|requirement| {
                    self.emit_region_requirement(&requirement.lhs, requirement.op, requirement.rhs)
                })
                .collect::<Result<Vec<_>, _>>()?;
            self.emit_region_selection(source, &region.name, baseline_ident, &conditions)?;
        }
        Ok(())
    }

    fn emit_region_selection(
        &self,
        source: &mut String,
        region_name: &str,
        baseline_ident: &str,
        conditions: &[String],
    ) -> Result<(), CodegenError> {
        let type_ident = region_type_ident(region_name)?;
        let event_ident = checked_ident(region_name, "region event")?;
        let predicate = if conditions.is_empty() {
            "true".to_string()
        } else {
            conditions.join(" && ")
        };
        writeln!(
            source,
            "        let Some(_{event_ident}_event) = {baseline_ident}.select::<{type_ident}>(|_| {predicate}) else {{"
        )
        .unwrap();
        writeln!(source, "            return Ok(None);").unwrap();
        writeln!(source, "        }};").unwrap();
        Ok(())
    }

    fn emit_object_selection(
        &self,
        source: &mut String,
        object: &ObjectDef,
    ) -> Result<(), CodegenError> {
        let object_name = checked_ident(&object.name, "object name")?;
        let collection_ident = format!("{object_name}_collection");
        let item_ident = format!("{object_name}_item");
        let count_ident = count_ident(&object.name)?;
        let attrs = self.attrs_needed_for_object(&object.name)?;

        writeln!(
            source,
            "        let {collection_ident} = event.collection({})?;",
            rust_string(&object.source)
        )
        .unwrap();
        writeln!(source, "        let mut {count_ident} = 0_u32;").unwrap();

        for output in &self.spec().outputs {
            if let Expr::LeadingAttr {
                object: output_object,
                ..
            } = &output.expr
            {
                if output_object == &object.name {
                    let output_name = checked_ident(&output.name, "leading output")?;
                    writeln!(source, "        let mut {output_name}: Option<f32> = None;").unwrap();
                }
            }
        }

        writeln!(source).unwrap();
        writeln!(
            source,
            "        for {item_ident} in {collection_ident}.iter() {{"
        )
        .unwrap();

        for attr in attrs {
            self.require_f32_attr(&object.name, &attr, "object attribute")?;
            let attr_ident = attr_ident(&object.name, &attr)?;
            writeln!(
                source,
                "            let {attr_ident} = {item_ident}.get::<f32>({})?;",
                rust_string(&attr)
            )
            .unwrap();
        }

        let condition = if object.cuts.is_empty() {
            "true".to_string()
        } else {
            object
                .cuts
                .iter()
                .map(|cut| self.emit_cut(object, cut))
                .collect::<Result<Vec<_>, _>>()?
                .join(" && ")
        };

        writeln!(source, "            if {condition} {{").unwrap();
        writeln!(source, "                {count_ident} += 1;").unwrap();

        for output in &self.spec().outputs {
            if let Expr::LeadingAttr {
                object: output_object,
                attr,
            } = &output.expr
            {
                if output_object == &object.name {
                    let output_name = checked_ident(&output.name, "leading output")?;
                    let attr_ident = attr_ident(&object.name, attr)?;
                    writeln!(source, "                {output_name} = Some(").unwrap();
                    writeln!(
                        source,
                        "                    {output_name}.map_or({attr_ident}, |lead| lead.max({attr_ident})),"
                    )
                    .unwrap();
                    writeln!(source, "                );").unwrap();
                }
            }
        }

        writeln!(source, "            }}").unwrap();
        writeln!(source, "        }}").unwrap();
        writeln!(source).unwrap();
        Ok(())
    }

    fn attrs_needed_for_object(&self, object_name: &str) -> Result<BTreeSet<String>, CodegenError> {
        let mut attrs = BTreeSet::new();
        let object = self.object(object_name)?;
        for cut in &object.cuts {
            collect_attr_names_for_current_object(&cut.lhs, object_name, &mut attrs)?;
        }
        for output in &self.spec().outputs {
            if let Expr::LeadingAttr { object, attr } = &output.expr {
                if object == object_name {
                    attrs.insert(attr.clone());
                }
            }
        }
        if !self.spec().models.is_empty() {
            for region in &self.spec().regions {
                for requirement in &region.require {
                    if let Expr::LeadingAttr { object, attr } = &requirement.lhs {
                        if object == object_name {
                            attrs.insert(attr.clone());
                        }
                    }
                }
            }
        }
        Ok(attrs)
    }

    fn emit_cut(&self, object: &ObjectDef, cut: &crate::Cut) -> Result<String, CodegenError> {
        let lhs = self.emit_cut_value_expr(&cut.lhs, &object.name)?;
        let op = cmp_op(cut.op);
        let rhs = f32_literal(cut.rhs.value);
        Ok(format!("({lhs} {op} {rhs})"))
    }

    fn emit_cut_value_expr(&self, expr: &Expr, object_name: &str) -> Result<String, CodegenError> {
        match expr {
            Expr::Attr { object, attr } if object == object_name => {
                attr_ident(object_name, attr)
            }
            Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
                "object cut references `{object}`; this slice only supports cuts on the object being selected"
            ))),
            Expr::Abs(inner) => Ok(format!("{}.abs()", self.emit_cut_value_expr(inner, object_name)?)),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "object cut expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn emit_region_requirement(
        &self,
        lhs: &Expr,
        op: CmpOp,
        rhs: f64,
    ) -> Result<String, CodegenError> {
        let Expr::Count(object) = lhs else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "region requirement `{lhs}` is not supported by this slice"
            )));
        };
        let lhs = count_ident(object)?;
        let rhs = checked_count_rhs(rhs, "region requirement")?;
        Ok(format!("{lhs} {} {rhs}_u32", cmp_op(op)))
    }

    fn emit_output_expr(&self, expr: &Expr, output_name: &str) -> Result<String, CodegenError> {
        match expr {
            Expr::Count(object) => count_ident(object),
            Expr::LeadingAttr { .. } => Ok(output_name.to_string()),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "output expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn output_type(&self, expr: &Expr) -> Result<&'static str, CodegenError> {
        match expr {
            Expr::Count(_) => Ok("u32"),
            Expr::LeadingAttr { .. } => Ok("f32"),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "output expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn validate_cut_expr(&self, object_name: &str, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::Attr { object, attr } if object == object_name => {
                self.require_f32_attr(object, attr, "object cut")?;
                Ok(())
            }
            Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
                "object `{object_name}` cut references `{object}`; this slice only supports cuts on the object being selected"
            ))),
            Expr::Abs(inner) => self.validate_cut_expr(object_name, inner),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "object cut expression `{other}` is not supported by this slice"
            ))),
        }
    }

    fn validate_count_expr(&self, expr: &Expr, context: &str) -> Result<(), CodegenError> {
        let Expr::Count(object) = expr else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context} expression `{expr}` is not supported by this slice"
            )));
        };
        self.object(object)?;
        Ok(())
    }

    fn require_f32_attr(
        &self,
        object_name: &str,
        attr: &str,
        context: &str,
    ) -> Result<(), CodegenError> {
        let object = self.object(object_name)?;
        if self
            .spec()
            .models
            .iter()
            .any(|model| self.model_output_matches_object_attr(model, &object.source, attr))
        {
            return Ok(());
        }
        let branch = format!("{}_{}", object.source, attr);
        let Some(info) = self.plan.read_branches.find(&branch) else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context}: branch `{branch}` was not present in the validated read schema"
            )));
        };
        if info.branch_type != BranchType::VecF32 {
            return Err(CodegenError::UnsupportedFeature(format!(
                "{context}: branch `{branch}` has type {:?}; this slice only emits f32 object reads",
                info.branch_type
            )));
        }
        Ok(())
    }

    fn object(&self, name: &str) -> Result<&ObjectDef, CodegenError> {
        self.spec()
            .objects
            .iter()
            .find(|object| object.name == name)
            .ok_or_else(|| {
                CodegenError::UnsupportedFeature(format!(
                    "object `{name}` is not defined in the analysis spec"
                ))
            })
    }

    fn validate_model_region_expr(&self, expr: &Expr, context: &str) -> Result<(), CodegenError> {
        match expr {
            Expr::Count(object) => {
                self.object(object)?;
                Ok(())
            }
            Expr::LeadingAttr { object, attr } => self.require_f32_attr(object, attr, context),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "{context} expression `{other}` is not supported by model-aware codegen"
            ))),
        }
    }

    fn emit_model_tag(&self, source: &mut String, model: &ModelDef) -> Result<(), CodegenError> {
        let type_ident = self.model_type_ident(model)?;
        let batch = self.model_batch_source(model)?;
        let (_, output_attr) = split_model_output(&model.output)?;

        writeln!(source).unwrap();
        writeln!(
            source,
            "#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]"
        )
        .unwrap();
        writeln!(source, "struct {type_ident};").unwrap();
        writeln!(source).unwrap();
        writeln!(source, "impl nano_analysis::ModelTag for {type_ident} {{").unwrap();
        writeln!(
            source,
            "    const NAME: &'static str = {};",
            rust_string(&model.name)
        )
        .unwrap();
        writeln!(
            source,
            "    const BATCH: &'static str = {};",
            rust_string(&batch)
        )
        .unwrap();
        writeln!(
            source,
            "    const OUTPUT: &'static str = {};",
            rust_string(output_attr)
        )
        .unwrap();
        writeln!(source, "}}").unwrap();
        Ok(())
    }

    fn emit_model_inference(
        &self,
        source: &mut String,
        model: &ModelDef,
    ) -> Result<(), CodegenError> {
        let model_ident = checked_ident(&model.name, "model name")?;
        let type_ident = self.model_type_ident(model)?;
        let batch = self.model_batch_source(model)?;
        let n_inputs = model.inputs.len();

        writeln!(
            source,
            "        let {model_ident}_collection = event.collection({}).map_err(gen_core_error)?;",
            rust_string(&batch)
        )
        .unwrap();
        writeln!(
            source,
            "        let mut {model_ident}_values = Vec::with_capacity({model_ident}_collection.len() * {n_inputs});"
        )
        .unwrap();
        writeln!(
            source,
            "        for {model_ident}_item in {model_ident}_collection.iter() {{"
        )
        .unwrap();
        for input in &model.inputs {
            self.emit_model_input_push(source, model, input)?;
        }
        writeln!(source, "        }}").unwrap();
        writeln!(
            source,
            "        let {model_ident}_features = nano_analysis::Features::<{type_ident}>::from_tensors(vec![nano_inference::Tensor {{"
        )
        .unwrap();
        writeln!(source, "            name: \"features\".to_string(),").unwrap();
        writeln!(
            source,
            "            shape: vec![{model_ident}_collection.len(), {n_inputs}],"
        )
        .unwrap();
        writeln!(
            source,
            "            data: nano_inference::TensorData::F32({model_ident}_values),"
        )
        .unwrap();
        writeln!(source, "        }}]);").unwrap();
        writeln!(
            source,
            "        let {model_ident}_baseline = nano_analysis::Ev::new(event)"
        )
        .unwrap();
        writeln!(source, "            .preselect(|_| true)").unwrap();
        writeln!(
            source,
            "            .expect(\"true generated preselection should always pass\");"
        )
        .unwrap();
        writeln!(
            source,
            "        let _{model_ident}_scored = {model_ident}_baseline.infer::<{type_ident}>(predictor, {model_ident}_features)?;"
        )
        .unwrap();
        writeln!(source).unwrap();
        Ok(())
    }

    fn emit_model_input_push(
        &self,
        source: &mut String,
        model: &ModelDef,
        input: &str,
    ) -> Result<(), CodegenError> {
        let model_ident = checked_ident(&model.name, "model name")?;
        let local_ident = format!("{model_ident}_{}", branch_ident(input)?);
        let branch_type = self.branch_type(input)?;
        if branch_type.is_vector() {
            let batch = self.model_batch_source(model)?;
            let Some((source_name, attr)) = input.split_once('_') else {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "model `{}` input `{input}` is not a supported object attribute branch",
                    model.name
                )));
            };
            if source_name != batch {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "model `{}` input `{input}` is a vector branch outside batch `{batch}`",
                    model.name
                )));
            }
            let value_expr = match branch_type {
                BranchType::VecI8 => format!(
                    "{model_ident}_item.get::<i8>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecU8 => format!(
                    "{model_ident}_item.get::<u8>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecI16 => format!(
                    "{model_ident}_item.get::<i16>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecU16 => format!(
                    "{model_ident}_item.get::<u16>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecI32 => format!(
                    "{model_ident}_item.get::<i32>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecU32 => format!(
                    "{model_ident}_item.get::<u32>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecI64 => format!(
                    "{model_ident}_item.get::<i64>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecU64 => format!(
                    "{model_ident}_item.get::<u64>({}).map(|value| value as f32)",
                    rust_string(attr)
                ),
                BranchType::VecF32 => {
                    format!("{model_ident}_item.get::<f32>({})", rust_string(attr))
                }
                other => {
                    return Err(CodegenError::UnsupportedFeature(format!(
                        "model `{}` input `{input}` has unsupported type {other:?}",
                        model.name
                    )));
                }
            };
            writeln!(
                source,
                "            let {local_ident} = {value_expr}.map_err(gen_core_error)?;"
            )
            .unwrap();
        } else {
            let value_expr = match branch_type {
                BranchType::I8 => format!(
                    "event.scalar::<i8>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::U8 => format!(
                    "event.scalar::<u8>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::I16 => format!(
                    "event.scalar::<i16>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::U16 => format!(
                    "event.scalar::<u16>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::I32 => format!(
                    "event.scalar::<i32>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::U32 => format!(
                    "event.scalar::<u32>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::I64 => format!(
                    "event.scalar::<i64>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::U64 => format!(
                    "event.scalar::<u64>({}).map(|value| value as f32)",
                    rust_string(input)
                ),
                BranchType::F32 => format!("event.scalar::<f32>({})", rust_string(input)),
                other => {
                    return Err(CodegenError::UnsupportedFeature(format!(
                        "model `{}` input `{input}` has unsupported type {other:?}",
                        model.name
                    )));
                }
            };
            writeln!(
                source,
                "            let {local_ident} = {value_expr}.map_err(gen_core_error)?;"
            )
            .unwrap();
        }
        writeln!(
            source,
            "            {model_ident}_values.push({local_ident});"
        )
        .unwrap();
        Ok(())
    }

    fn emit_model_object_selection(
        &self,
        source: &mut String,
        object_name: &str,
    ) -> Result<(), CodegenError> {
        let object = self.object(object_name)?;
        let object_name = checked_ident(&object.name, "object name")?;
        let collection_ident = format!("{object_name}_collection");
        let item_ident = format!("{object_name}_item");
        let count_ident = count_ident(&object.name)?;
        let attrs = self.attrs_needed_for_object(&object.name)?;

        writeln!(
            source,
            "        let {collection_ident} = event.collection({}).map_err(gen_core_error)?;",
            rust_string(&object.source)
        )
        .unwrap();
        writeln!(source, "        let mut {count_ident} = 0_u32;").unwrap();

        for (object, attr) in self.leading_exprs_for_object(&object.name)? {
            let ident = leading_attr_ident(&object, &attr)?;
            writeln!(source, "        let mut {ident}: Option<f32> = None;").unwrap();
        }

        writeln!(source).unwrap();
        writeln!(
            source,
            "        for {item_ident} in {collection_ident}.iter() {{"
        )
        .unwrap();

        for attr in attrs {
            self.require_f32_attr(&object.name, &attr, "object attribute")?;
            let attr_ident = attr_ident(&object.name, &attr)?;
            writeln!(
                source,
                "            let {attr_ident} = {item_ident}.get::<f32>({}).map_err(gen_core_error)?;",
                rust_string(&attr)
            )
            .unwrap();
        }

        let condition = if object.cuts.is_empty() {
            "true".to_string()
        } else {
            object
                .cuts
                .iter()
                .map(|cut| self.emit_cut(object, cut))
                .collect::<Result<Vec<_>, _>>()?
                .join(" && ")
        };

        writeln!(source, "            if {condition} {{").unwrap();
        writeln!(source, "                {count_ident} += 1;").unwrap();

        for (object, attr) in self.leading_exprs_for_object(&object.name)? {
            let leading_ident = leading_attr_ident(&object, &attr)?;
            let attr_ident = attr_ident(&object, &attr)?;
            writeln!(source, "                {leading_ident} = Some(").unwrap();
            writeln!(
                source,
                "                    {leading_ident}.map_or({attr_ident}, |lead| lead.max({attr_ident})),"
            )
            .unwrap();
            writeln!(source, "                );").unwrap();
        }

        writeln!(source, "            }}").unwrap();
        writeln!(source, "        }}").unwrap();
        writeln!(source).unwrap();
        Ok(())
    }

    fn emit_model_region_requirement(
        &self,
        lhs: &Expr,
        op: CmpOp,
        rhs: f64,
        source: &mut String,
        unwrapped_leading: &mut BTreeSet<(String, String)>,
    ) -> Result<String, CodegenError> {
        match lhs {
            Expr::Count(object) => {
                let lhs = count_ident(object)?;
                let rhs = checked_count_rhs(rhs, "region requirement")?;
                Ok(format!("{lhs} {} {rhs}_u32", cmp_op(op)))
            }
            Expr::LeadingAttr { object, attr } => {
                let key = (object.clone(), attr.clone());
                let lhs = leading_attr_ident(object, attr)?;
                if unwrapped_leading.insert(key) {
                    writeln!(source, "        let Some({lhs}) = {lhs} else {{").unwrap();
                    writeln!(source, "            return Ok(None);").unwrap();
                    writeln!(source, "        }};").unwrap();
                }
                Ok(format!("{lhs} {} {}", cmp_op(op), f32_literal(rhs)))
            }
            other => Err(CodegenError::UnsupportedFeature(format!(
                "region requirement `{other}` is not supported by model-aware codegen"
            ))),
        }
    }

    fn emit_model_output_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Count(object) => count_ident(object),
            Expr::LeadingAttr { object, attr } => leading_attr_ident(object, attr),
            other => Err(CodegenError::UnsupportedFeature(format!(
                "output expression `{other}` is not supported by model-aware codegen"
            ))),
        }
    }

    fn leading_region_exprs(&self) -> BTreeSet<(String, String)> {
        self.spec()
            .regions
            .iter()
            .flat_map(|region| &region.require)
            .filter_map(|requirement| match &requirement.lhs {
                Expr::LeadingAttr { object, attr } => Some((object.clone(), attr.clone())),
                _ => None,
            })
            .collect()
    }

    fn leading_exprs_for_object(
        &self,
        object_name: &str,
    ) -> Result<BTreeSet<(String, String)>, CodegenError> {
        let mut exprs = BTreeSet::new();
        for output in &self.spec().outputs {
            if let Expr::LeadingAttr { object, attr } = &output.expr {
                if object == object_name {
                    exprs.insert((object.clone(), attr.clone()));
                }
            }
        }
        for region in &self.spec().regions {
            for requirement in &region.require {
                if let Expr::LeadingAttr { object, attr } = &requirement.lhs {
                    if object == object_name {
                        exprs.insert((object.clone(), attr.clone()));
                    }
                }
            }
        }
        for (object, attr) in &exprs {
            self.require_f32_attr(object, attr, "leading attribute")?;
        }
        Ok(exprs)
    }

    fn model_type_ident(&self, model: &ModelDef) -> Result<String, CodegenError> {
        upper_camel_ident(&model.name, "model type")
    }

    fn model_batch_source(&self, model: &ModelDef) -> Result<String, CodegenError> {
        if let Some(object) = self
            .spec()
            .objects
            .iter()
            .find(|object| object.name == model.batch)
        {
            return Ok(object.source.clone());
        }
        if self
            .spec()
            .objects
            .iter()
            .any(|object| object.source == model.batch)
        {
            return Ok(model.batch.clone());
        }
        Err(CodegenError::UnsupportedFeature(format!(
            "model `{}` batch `{}` is not defined",
            model.name, model.batch
        )))
    }

    fn model_output_matches_object_attr(
        &self,
        model: &ModelDef,
        object_source: &str,
        attr: &str,
    ) -> bool {
        split_model_output(&model.output)
            .is_ok_and(|(source, output_attr)| source == object_source && output_attr == attr)
    }

    fn validate_model_input(&self, model: &ModelDef, input: &str) -> Result<(), CodegenError> {
        let branch_type = self.branch_type(input)?;
        if branch_type.is_vector() {
            let batch = self.model_batch_source(model)?;
            let Some((source, _)) = input.split_once('_') else {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "model `{}` input `{input}` is not a supported object attribute branch",
                    model.name
                )));
            };
            if source != batch {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "model `{}` input `{input}` is a vector branch outside batch `{batch}`",
                    model.name
                )));
            }
        }
        Ok(())
    }

    fn branch_type(&self, branch: &str) -> Result<BranchType, CodegenError> {
        self.plan
            .read_branches
            .find(branch)
            .map(|info| info.branch_type)
            .ok_or_else(|| {
                CodegenError::UnsupportedFeature(format!(
                    "branch `{branch}` was not present in the validated read schema"
                ))
            })
    }
}

fn collect_attr_names_for_current_object(
    expr: &Expr,
    object_name: &str,
    attrs: &mut BTreeSet<String>,
) -> Result<(), CodegenError> {
    match expr {
        Expr::Attr { object, attr } if object == object_name => {
            attrs.insert(attr.clone());
            Ok(())
        }
        Expr::Attr { object, .. } => Err(CodegenError::UnsupportedFeature(format!(
            "object `{object_name}` cut references `{object}`; this slice only supports cuts on the object being selected"
        ))),
        Expr::Abs(inner) => collect_attr_names_for_current_object(inner, object_name, attrs),
        other => Err(CodegenError::UnsupportedFeature(format!(
            "object cut expression `{other}` is not supported by this slice"
        ))),
    }
}

fn count_ident(object_name: &str) -> Result<String, CodegenError> {
    Ok(format!("n_{}", checked_ident(object_name, "count object")?))
}

fn attr_ident(object_name: &str, attr: &str) -> Result<String, CodegenError> {
    Ok(format!(
        "{}_{}",
        checked_ident(object_name, "attribute object")?,
        checked_ident(attr, "attribute")?
    ))
}

fn leading_attr_ident(object_name: &str, attr: &str) -> Result<String, CodegenError> {
    Ok(format!(
        "leading_{}_{}",
        checked_ident(object_name, "leading object")?,
        checked_ident(attr, "leading attribute")?
    ))
}

fn region_type_ident(region_name: &str) -> Result<String, CodegenError> {
    Ok(format!(
        "{}Region",
        upper_camel_ident(region_name, "region type")?
    ))
}

fn branch_ident(branch: &str) -> Result<String, CodegenError> {
    let ident = branch.to_ascii_lowercase();
    checked_ident(&ident, "branch identifier")
}

fn upper_camel_ident(value: &str, context: &str) -> Result<String, CodegenError> {
    checked_ident(value, context)?;
    let mut ident = String::new();
    for part in value.split('_') {
        if part.is_empty() {
            return Err(CodegenError::InvalidIdentifier {
                context: context.to_string(),
                value: value.to_string(),
            });
        }
        let mut chars = part.chars();
        let Some(first) = chars.next() else {
            return Err(CodegenError::InvalidIdentifier {
                context: context.to_string(),
                value: value.to_string(),
            });
        };
        ident.push(first.to_ascii_uppercase());
        ident.extend(chars);
    }
    checked_ident(&ident, context)
}

fn split_model_output(output: &str) -> Result<(&str, &str), CodegenError> {
    let Some((source, attr)) = output.split_once('_') else {
        return Err(CodegenError::UnsupportedFeature(format!(
            "model output `{output}` is not a supported per-object column"
        )));
    };
    Ok((source, attr))
}

fn checked_ident(value: &str, context: &str) -> Result<String, CodegenError> {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return Err(CodegenError::InvalidIdentifier {
            context: context.to_string(),
            value: value.to_string(),
        });
    };
    if !(first == '_' || first.is_ascii_alphabetic())
        || !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        || rust_keywords().contains_key(value)
    {
        return Err(CodegenError::InvalidIdentifier {
            context: context.to_string(),
            value: value.to_string(),
        });
    }
    Ok(value.to_string())
}

fn rust_keywords() -> BTreeMap<&'static str, ()> {
    [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn",
    ]
    .into_iter()
    .map(|keyword| (keyword, ()))
    .collect()
}

fn cmp_op(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Gt => ">",
        CmpOp::Ge => ">=",
        CmpOp::Lt => "<",
        CmpOp::Le => "<=",
        CmpOp::Eq => "==",
        CmpOp::Ne => "!=",
    }
}

fn f32_literal(value: f64) -> String {
    format!("{value:?}_f32")
}

fn checked_count_rhs(value: f64, context: &str) -> Result<u32, CodegenError> {
    if value.is_finite() && value >= 0.0 && value.fract() == 0.0 && value <= u32::MAX as f64 {
        Ok(value as u32)
    } else {
        Err(CodegenError::UnsupportedFeature(format!(
            "{context}: count comparison rhs `{value}` is not a non-negative u32 integer"
        )))
    }
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{validate, AnalysisSpec, Catalogue};

    const MUON_SPEC: &str = include_str!("../examples/muon.toml");
    const MUON_TAGGER_SPEC: &str = include_str!("../examples/muon_tagger.toml");
    const NANOV9_CATALOGUE: &str = include_str!("../../../configs/branches/nanov9.yaml");

    #[test]
    fn generates_muon_producer_source() {
        let spec = AnalysisSpec::from_toml_str(MUON_SPEC).unwrap();
        let catalogue = Catalogue::from_nanoaod_yaml_str(NANOV9_CATALOGUE, "v9").unwrap();
        let plan = validate(&spec, &catalogue).unwrap();
        let source = generate_producer_source(&plan).unwrap();

        assert!(source.contains("pub struct GenRow"));
        assert!(source.contains("pub struct GeneratedProducer;"));
        assert!(source.contains("struct SignalRegion;"));
        assert!(source.contains("impl nano_analysis::Region for SignalRegion"));
        assert!(source.contains("let good_muon_pt = good_muon_item.get::<f32>(\"pt\")?;"));
        assert!(source.contains("if (good_muon_pt > 30.0_f32) && (good_muon_eta.abs() < 2.4_f32)"));
        assert!(source.contains("let baseline = nano_analysis::Ev::new(event)"));
        assert!(source.contains("baseline.select::<SignalRegion>(|_| n_good_muon >= 1_u32)"));
        assert!(source.contains("n_good_muon,"));
        assert!(source.contains("lead_muon_pt,"));
    }

    #[test]
    fn generates_model_aware_muon_tagger_producer_source() {
        let spec = AnalysisSpec::from_toml_str(MUON_TAGGER_SPEC).unwrap();
        let catalogue = Catalogue::from_nanoaod_yaml_str(NANOV9_CATALOGUE, "v9").unwrap();
        let plan = validate(&spec, &catalogue).unwrap();
        let source = generate_producer_source(&plan).unwrap();

        assert!(source.contains("impl nano_analysis::ModelTag for MuonTagger"));
        assert!(source.contains(
            "pub fn analyze(event: &nano_core::Event, predictor: &impl nano_inference::Predictor)"
        ));
        assert!(source.contains("nano_analysis::Features::<MuonTagger>::from_tensors"));
        assert!(source.contains(
            "muon_tagger_baseline.infer::<MuonTagger>(predictor, muon_tagger_features)?;"
        ));
        assert!(source
            .contains("let Some(leading_good_muon_topscore) = leading_good_muon_topscore else"));
        assert!(source.contains(
            "muon_tagger_baseline.select::<SignalRegion>(|_| n_good_muon >= 1_u32 && leading_good_muon_topscore > 0.5_f32)"
        ));
    }
}
