use std::path::{Path, PathBuf};

use nano_cli::{run, CliError, ErrorKind, Output, ValidationErrorKind};

fn repo_path(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(relative)
}

#[test]
fn validate_muon_toml_reports_resolved_summary() {
    let spec = repo_path("crates/nano-spec/examples/muon.toml");
    let output = run(["validate", spec.to_str().unwrap()]).expect("validate command");

    let Output::Validate(report) = output else {
        panic!("expected validate report");
    };

    assert_eq!(report.analysis.name, "muon_demo");
    assert_eq!(report.analysis.objects[0].name, "good_muon");
    assert_eq!(report.analysis.regions, vec!["signal"]);
    assert_eq!(
        report
            .read_branches
            .iter()
            .map(|branch| (branch.name.as_str(), branch.branch_type.as_str()))
            .collect::<Vec<_>>(),
        vec![
            ("nMuon", "U32"),
            ("Muon_eta", "VecF32"),
            ("Muon_pt", "VecF32")
        ]
    );
}

#[test]
fn validate_broken_spec_fails_with_structured_errors() {
    let spec = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/broken-muon.toml");
    let error = run(["--json", "validate", spec.to_str().unwrap()])
        .expect_err("broken spec should fail validation");

    assert_eq!(error.kind, ErrorKind::Validation);
    assert_validation_kind(&error, ValidationErrorKind::MissingUnit);
    assert_validation_kind(&error, ValidationErrorKind::MissingBranch);
    assert_validation_kind(&error, ValidationErrorKind::UndefinedObject);

    let json = nano_cli::render_json_error(&error).expect("JSON error");
    assert!(json.contains("\"kind\": \"validation\""));
    assert!(json.contains("\"kind\": \"missing_unit\""));
    assert!(json.contains("\"branch\": \"Muon_nope\""));
    assert!(json.contains("\"object\": \"ghost_muon\""));
}

#[test]
fn branches_muon_toml_reports_derived_read_branches() {
    let spec = repo_path("crates/nano-spec/examples/muon.toml");
    let output = run(["branches", spec.to_str().unwrap()]).expect("branches command");

    let Output::Branches(report) = output else {
        panic!("expected branches report");
    };

    assert_eq!(
        report
            .branches
            .iter()
            .map(|branch| format!("{} {}", branch.name, branch.branch_type))
            .collect::<Vec<_>>(),
        vec!["nMuon U32", "Muon_eta VecF32", "Muon_pt VecF32"]
    );

    let json = nano_cli::render_json_output(&Output::Branches(report)).expect("JSON branches");
    assert!(json.contains("\"command\": \"branches\""));
    assert!(json.contains("\"name\": \"Muon_pt\""));
}

#[test]
fn codegen_muon_toml_emits_generated_producer_source() {
    let spec = repo_path("crates/nano-spec/examples/muon.toml");
    let output = run(["codegen", spec.to_str().unwrap()]).expect("codegen command");

    let Output::Codegen(report) = output else {
        panic!("expected codegen report");
    };

    assert!(report
        .source
        .contains("// @generated by nano-spec from analysis `muon_demo`"));
    assert!(report.source.contains("pub struct GenRow"));
    assert!(report.source.contains("pub lead_muon_pt: f32"));
    assert!(report.source.contains("event.collection(\"Muon\")?"));
}

#[test]
fn inspect_bundled_root_file_lists_ttrees() {
    let root_file = repo_path("crates/root-io/src/test_data/simple.root");
    let output = run(["inspect", root_file.to_str().unwrap()]).expect("inspect command");

    let Output::Inspect(report) = output else {
        panic!("expected inspect report");
    };

    assert!(report
        .trees
        .iter()
        .any(|tree| tree.name == "tree" && tree.entries > 0));

    let json = nano_cli::render_json_output(&Output::Inspect(report)).expect("JSON inspect");
    assert!(json.contains("\"command\": \"inspect\""));
    assert!(json.contains("\"name\": \"tree\""));
}

fn assert_validation_kind(error: &CliError, kind: ValidationErrorKind) {
    assert!(
        error
            .validation_errors
            .iter()
            .any(|validation_error| validation_error.kind == kind),
        "missing {kind:?} in {error:#?}"
    );
}
